### ISSUE TITLE
Installing/building using flake fails.

### ISSUE THREAD

**Issue by wvffle** [pimalaya/himalaya#502] opened 2024-11-14 09:35 UTC
When I try to install himalaya using flake, it fails the same way as in the CI:

https://github.com/pimalaya/himalaya/actions/runs/11785895772/job/32828055557#step:5:1875

**Comment by soywod** [comment] 2024-11-14 09:45
No luck, it just broke yesterday due to my last commit. Looks like nix cannot find path to the git repo, in order to collect infos like git branch or revision.

**Comment by KoviRobi** [comment] 2024-11-20 00:29
Ah yes, Nix clones the git repository, but doesn't include the `.git` directory in the build environment, for reproducibility/purity reasons, as the `.git` directory is not reproducible (e.g. it contains info about remote branches). You probably want to add some environment variable override, and set that from the nix flake.

**Comment by soywod** [comment] 2024-11-20 09:15
I have hard time to see how to automatically take git information then. I would like to avoid manual env var or file. Any idea?

**Comment by soywod** [comment] 2024-11-20 09:43
Just found something interesting, looks like git infos are already available (at least in flakes):

https://stackoverflow.com/questions/67025103/how-inject-git-revision-into-nix-derivation

**Comment by KoviRobi** [comment] 2024-11-20 10:04
Yes I get you, manual versions are annoying -- what I would do is use the `sourceInfo.*` bits to make a hash/date based version, and for your CI, I would run `git describe`, and pass the output of that into the flake -- I will make an example when I'm at my desktop in a couple of hours :)

**Comment by soywod** [comment] 2024-11-20 15:10
Fixed by https://github.com/pimalaya/himalaya/commit/36f3690cbaf473a4be880642ff978d84769b4c61, so this issue can be close. Alternative are welcomed!

**Closed by soywod** 2024-11-20 15:10 UTC
